## Initialize the sentences

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## One hot representation of sentences 

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### Vocabulary size
voc_size=10000

## One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5555, 3474, 584, 9679], [5555, 3474, 584, 7154], [5555, 664, 584, 5203], [9955, 3819, 2672, 9034, 3275], [9955, 3819, 2672, 9034, 4374], [7318, 5555, 1198, 584, 9137], [9861, 431, 3708, 9034]]


## Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5555 3474  584 9679]
 [   0    0    0    0 5555 3474  584 7154]
 [   0    0    0    0 5555  664  584 5203]
 [   0    0    0 9955 3819 2672 9034 3275]
 [   0    0    0 9955 3819 2672 9034 4374]
 [   0    0    0 7318 5555 1198  584 9137]
 [   0    0    0    0 9861  431 3708 9034]]


In [9]:
dim=10

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

W0520 21:08:27.767035 20020 deprecation.py:506] From C:\Users\prasanna\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

[[[ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339
   -0.00335724  0.00647225 -0.03577835 -0.01066927  0.0392987 ]
  [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339
   -0.00335724  0.00647225 -0.03577835 -0.01066927  0.0392987 ]
  [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339
   -0.00335724  0.00647225 -0.03577835 -0.01066927  0.0392987 ]
  [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339
   -0.00335724  0.00647225 -0.03577835 -0.01066927  0.0392987 ]
  [ 0.02927898  0.04586954 -0.04399697 -0.04199994  0.03021074
    0.02310636 -0.00024169  0.0477975   0.03913939 -0.03087286]
  [-0.00531916  0.02056494  0.04681528 -0.0072635  -0.02848557
   -0.00554936 -0.01956245  0.00524808  0.01599378  0.01626142]
  [-0.04645449 -0.04844628  0.03757003  0.04627826 -0.01789395
    0.03312034 -0.0319527   0.01619252 -0.01048749  0.0348173 ]
  [-0.04059903  0.00561936  0.00663126 -0.02376053 -0.044642
   -0.02572603 -0.01136892 -0.04327792 -0.04133896  0.

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 5555, 3474,  584, 9679])

In [13]:
print(model.predict(embedded_docs)[0])

[[ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339  -0.00335724
   0.00647225 -0.03577835 -0.01066927  0.0392987 ]
 [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339  -0.00335724
   0.00647225 -0.03577835 -0.01066927  0.0392987 ]
 [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339  -0.00335724
   0.00647225 -0.03577835 -0.01066927  0.0392987 ]
 [ 0.01727048 -0.00728266  0.02865675 -0.03284221  0.0122339  -0.00335724
   0.00647225 -0.03577835 -0.01066927  0.0392987 ]
 [ 0.02927898  0.04586954 -0.04399697 -0.04199994  0.03021074  0.02310636
  -0.00024169  0.0477975   0.03913939 -0.03087286]
 [-0.00531916  0.02056494  0.04681528 -0.0072635  -0.02848557 -0.00554936
  -0.01956245  0.00524808  0.01599378  0.01626142]
 [-0.04645449 -0.04844628  0.03757003  0.04627826 -0.01789395  0.03312034
  -0.0319527   0.01619252 -0.01048749  0.0348173 ]
 [-0.04059903  0.00561936  0.00663126 -0.02376053 -0.044642   -0.02572603
  -0.01136892 -0.04327792 -0.04133896  0.04945506]]